-- QBC SUPABASE MASTER SETUP
-- Description: Complete production-ready database migration (TRUE MASTER VERSION)
-- Version: 2.0.0
-- Date: 2024-05-24

-- ==========================================
-- 1. EXTENSIONS & FUNCTIONS
-- ==========================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- ==========================================
-- 2. CORE TABLES
-- ==========================================

-- work_orders
CREATE TABLE IF NOT EXISTS public.work_orders (
    work_order text PRIMARY KEY,
    id uuid UNIQUE DEFAULT gen_random_uuid(),
    description text,
    status text,
    pwa_engineer text,
    target_start_date timestamptz,
    target_finish_date timestamptz,
    location text,
    latitude float8,
    longitude float8,
    is_sent_to_fab boolean DEFAULT false,
    fab_history jsonb DEFAULT '[]'::jsonb,
    style_settings jsonb DEFAULT '{}'::jsonb,
    reported_by text,
    reported_date timestamptz,
    status_update_date timestamptz,
    qbc_comments text,
    ro text,
    tdp text,
    application_date timestamptz,
    tdp_status text,
    tdp_expiry_date timestamptz,
    media_announcement text,
    last_modified_at timestamptz DEFAULT now(),
    priority text DEFAULT 'Normal',
    month text,
    completion_status text,
    ready_for_installation boolean DEFAULT false,
    installation_status text DEFAULT 'Pending',
    assigned_team text,
    assigned_date timestamptz,
    planned_installation_date date,
    actual_installation_date date,
    dispatch_time timestamptz,
    dispatch_user text,
    sequence_order integer,
    created_at timestamptz DEFAULT now()
);

-- profiles
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email text UNIQUE NOT NULL,
    full_name text,
    mobile text,
    position text,
    is_approved boolean DEFAULT false,
    is_admin boolean DEFAULT false,
    role text DEFAULT 'User',
    created_at timestamptz DEFAULT now()
);

-- manufacturing
CREATE TABLE IF NOT EXISTS public.manufacturing (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    work_order_number text REFERENCES public.work_orders(work_order) ON DELETE CASCADE,
    road_catg text,
    sign_material text,
    sign_type text,
    sign_ref text,
    sign_shape text,
    sign_size text,
    sign_qty text,
    post_type text,
    post_height text,
    post_qty text,
    found_size text,
    found_qty text,
    fab_status text,
    installation_date date,
    scrap_removal text,
    fab_details text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- photos (Legacy/Compatibility)
CREATE TABLE IF NOT EXISTS public.photos (
    work_order text PRIMARY KEY REFERENCES public.work_orders(work_order) ON DELETE CASCADE,
    url text NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- ai_settings
CREATE TABLE IF NOT EXISTS public.ai_settings (
    id integer PRIMARY KEY DEFAULT 1,
    ai_enabled boolean DEFAULT true,
    provider_name text,
    ai_model text,
    api_base_url text,
    api_key text,
    minutes_per_sign integer DEFAULT 45,
    default_grouping_instructions text,
    updated_at timestamptz DEFAULT now(),
    updated_by uuid REFERENCES auth.users(id)
);

-- exported_pdfs
CREATE TABLE IF NOT EXISTS public.exported_pdfs (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    work_order text,
    filename text NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- project_boundaries
CREATE TABLE IF NOT EXISTS public.project_boundaries (
    id integer PRIMARY KEY,
    name text,
    geojson jsonb,
    style_settings jsonb,
    created_at timestamptz DEFAULT now()
);

-- ==========================================
-- 3. REMINDERS & FOLLOW-UP
-- ==========================================

-- work_order_reminders
CREATE TABLE IF NOT EXISTS public.work_order_reminders (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    work_order_number text REFERENCES public.work_orders(work_order) ON DELETE CASCADE,
    work_order_title text,
    title text NOT NULL,
    reminder_datetime timestamptz NOT NULL,
    reason text,
    custom_reason text,
    notes text,
    priority text DEFAULT 'Normal',
    status text DEFAULT 'upcoming',
    assigned_to uuid REFERENCES public.profiles(id),
    assigned_to_name text,
    alarm_enabled boolean DEFAULT true,
    calendar_enabled boolean DEFAULT true,
    desktop_notif boolean DEFAULT true,
    email_enabled boolean DEFAULT false,
    snoozed_until timestamptz,
    snooze_count integer DEFAULT 0,
    is_pinned boolean DEFAULT false,
    photo_count integer DEFAULT 0,
    created_by uuid DEFAULT auth.uid() REFERENCES public.profiles(id),
    created_by_name text,
    updated_by uuid DEFAULT auth.uid() REFERENCES public.profiles(id),
    updated_at timestamptz DEFAULT now(),
    completed_at timestamptz,
    completed_by uuid REFERENCES public.profiles(id),
    created_at timestamptz DEFAULT now()
);

-- reminder_photos
CREATE TABLE IF NOT EXISTS public.reminder_photos (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    reminder_id uuid REFERENCES public.work_order_reminders(id) ON DELETE CASCADE,
    storage_path text NOT NULL,
    public_url text NOT NULL,
    file_name text,
    file_size integer,
    mime_type text,
    caption text,
    sort_order integer DEFAULT 0,
    uploaded_by uuid DEFAULT auth.uid() REFERENCES public.profiles(id),
    created_at timestamptz DEFAULT now()
);

-- reminder_activity_log
CREATE TABLE IF NOT EXISTS public.reminder_activity_log (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    reminder_id uuid REFERENCES public.work_order_reminders(id) ON DELETE CASCADE,
    user_id uuid DEFAULT auth.uid() REFERENCES auth.users(id),
    username text,
    action text NOT NULL,
    previous_value jsonb,
    new_value jsonb,
    created_at timestamptz DEFAULT now()
);

-- reminder_notifications
CREATE TABLE IF NOT EXISTS public.reminder_notifications (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    reminder_id uuid REFERENCES public.work_order_reminders(id) ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users(id),
    title text,
    message text,
    read boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

-- reminder_snooze_history
CREATE TABLE IF NOT EXISTS public.reminder_snooze_history (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    reminder_id uuid REFERENCES public.work_order_reminders(id) ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users(id),
    snoozed_until timestamptz NOT NULL,
    duration_minutes integer,
    created_at timestamptz DEFAULT now()
);

-- followup_notes
CREATE TABLE IF NOT EXISTS public.followup_notes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    body text NOT NULL,
    color text DEFAULT 'yellow',
    rotation_deg numeric DEFAULT 0,
    created_by uuid DEFAULT auth.uid() REFERENCES public.profiles(id),
    created_by_name text,
    is_archived boolean DEFAULT false,
    work_order_number text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- followup_note_photos
CREATE TABLE IF NOT EXISTS public.followup_note_photos (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    note_id uuid REFERENCES public.followup_notes(id) ON DELETE CASCADE,
    storage_path text NOT NULL,
    public_url text NOT NULL,
    file_name text,
    uploaded_by uuid DEFAULT auth.uid() REFERENCES public.profiles(id),
    created_at timestamptz DEFAULT now()
);

-- ==========================================
-- 4. INSTALLATION MODULE
-- ==========================================

-- installation_teams
CREATE TABLE IF NOT EXISTS public.installation_teams (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    team_name text UNIQUE NOT NULL,
    supervisor text,
    crew_size integer,
    capacity_per_day integer,
    vehicle text,
    status text DEFAULT 'Active',
    created_by uuid DEFAULT auth.uid() REFERENCES public.profiles(id),
    created_at timestamptz DEFAULT now()
);

-- installation_records
CREATE TABLE IF NOT EXISTS public.installation_records (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    work_order text NOT NULL,
    team_name text,
    status text,
    completion_date timestamptz,
    recorded_by text,
    created_by uuid DEFAULT auth.uid() REFERENCES public.profiles(id),
    created_at timestamptz DEFAULT now()
);

-- installation_activities
CREATE TABLE IF NOT EXISTS public.installation_activities (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    work_order text,
    action text NOT NULL,
    user_name text,
    timestamp timestamptz DEFAULT now()
);

-- installation_packages
CREATE TABLE IF NOT EXISTS public.installation_packages (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    package_name text NOT NULL,
    team_id uuid REFERENCES public.installation_teams(id),
    planned_date date,
    status text DEFAULT 'Draft',
    created_at timestamptz DEFAULT now()
);

-- installation_programs
CREATE TABLE IF NOT EXISTS public.installation_programs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    program_name text NOT NULL,
    start_date date,
    end_date date,
    created_at timestamptz DEFAULT now()
);

-- installation_groups
CREATE TABLE IF NOT EXISTS public.installation_groups (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    group_name text NOT NULL,
    road_name text,
    road_direction text,
    chainage_from text,
    chainage_to text,
    assigned_team_id uuid REFERENCES public.installation_teams(id),
    color_hex text DEFAULT '#00c9b1',
    sign_count integer DEFAULT 0,
    estimated_duration_hours numeric,
    ai_generated boolean DEFAULT false,
    manually_modified boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

-- installation_group_members
CREATE TABLE IF NOT EXISTS public.installation_group_members (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    group_id uuid REFERENCES public.installation_groups(id) ON DELETE CASCADE,
    work_order_id uuid REFERENCES public.work_orders(id),
    sequence_order integer,
    created_at timestamptz DEFAULT now()
);

-- installation_photos
CREATE TABLE IF NOT EXISTS public.installation_photos (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    work_order text NOT NULL,
    category text NOT NULL,
    url text NOT NULL,
    uploaded_by uuid DEFAULT auth.uid() REFERENCES public.profiles(id),
    created_at timestamptz DEFAULT now()
);

-- ==========================================
-- 5. WORK ORDER EXTENSIONS
-- ==========================================

-- work_order_attachments
CREATE TABLE IF NOT EXISTS public.work_order_attachments (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    work_order text REFERENCES public.work_orders(work_order) ON DELETE CASCADE,
    url text NOT NULL,
    filename text,
    file_type text,
    uploader_id uuid REFERENCES auth.users(id),
    created_at timestamptz DEFAULT now()
);

-- work_order_comments
CREATE TABLE IF NOT EXISTS public.work_order_comments (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    work_order text REFERENCES public.work_orders(work_order) ON DELETE CASCADE,
    content text NOT NULL,
    author_id uuid REFERENCES auth.users(id),
    author_name text,
    created_at timestamptz DEFAULT now()
);

-- ==========================================
-- 6. LOGS & UTILITIES
-- ==========================================

-- audit_logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES auth.users(id),
    user_email text,
    user_name text,
    action text NOT NULL,
    details text,
    work_order text,
    created_at timestamptz DEFAULT now()
);

-- notifications
CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid REFERENCES auth.users(id),
    user_name text,
    action_text text,
    work_order text,
    category text DEFAULT 'system',
    read boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

-- map_history
CREATE TABLE IF NOT EXISTS public.map_history (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    action text NOT NULL,
    data jsonb,
    user_id uuid REFERENCES auth.users(id),
    created_at timestamptz DEFAULT now()
);

-- ==========================================
-- 7. CONSTRAINTS, INDEXES & TRIGGERS
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_wo_status ON public.work_orders (status);
CREATE INDEX IF NOT EXISTS idx_rem_datetime ON public.work_order_reminders (reminder_datetime);
CREATE INDEX IF NOT EXISTS idx_audit_created ON public.audit_logs (created_at);
CREATE INDEX IF NOT EXISTS idx_mfg_wo ON public.manufacturing (work_order_number);

CREATE TRIGGER set_updated_at_manufacturing BEFORE UPDATE ON public.manufacturing
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ==========================================
-- 8. RLS POLICIES (FULL COVERAGE)
-- ==========================================
ALTER TABLE public.work_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manufacturing ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_order_reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.followup_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.installation_teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.installation_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.installation_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exported_pdfs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reminder_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reminder_activity_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reminder_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reminder_snooze_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.followup_note_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.installation_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.installation_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.installation_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.installation_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.installation_group_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_order_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_order_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.map_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_boundaries ENABLE ROW LEVEL SECURITY;

-- 8.1. PUBLIC READ / AUTH SELECT (Application needs frequent read)
CREATE POLICY "Auth Read All" ON public.work_orders FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Auth Read All" ON public.profiles FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Auth Read All" ON public.installation_teams FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Auth Read All" ON public.installation_records FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Auth Read All" ON public.manufacturing FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Auth Read All" ON public.photos FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Auth Read All" ON public.project_boundaries FOR SELECT USING (auth.role() = 'authenticated');

-- 8.2. MANAGE OWN (Owner based)
CREATE POLICY "Manage Own Profile" ON public.profiles FOR ALL USING (auth.uid() = id);
CREATE POLICY "Manage Own Reminders" ON public.work_order_reminders FOR ALL USING (auth.uid() = created_by OR auth.uid() = assigned_to);
CREATE POLICY "Manage Own Notes" ON public.followup_notes FOR ALL USING (auth.uid() = created_by);
CREATE POLICY "Manage Own Teams" ON public.installation_teams FOR ALL USING (auth.uid() = created_by);
CREATE POLICY "Manage Own Records" ON public.installation_records FOR ALL USING (auth.uid() = created_by);
CREATE POLICY "Manage Own Photos" ON public.installation_photos FOR ALL USING (auth.uid() = uploaded_by);
CREATE POLICY "Manage Own Attachment" ON public.work_order_attachments FOR ALL USING (auth.uid() = uploader_id);

-- 8.3. AUTHENTICATED MANAGE (Broad access for app logic)
CREATE POLICY "Auth Manage Work Orders" ON public.work_orders FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth Manage Manufacturing" ON public.manufacturing FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth Manage Audit" ON public.audit_logs FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth Manage Notifications" ON public.notifications FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth Manage PDFs" ON public.exported_pdfs FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth Manage Maps" ON public.map_history FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth Manage Boundaries" ON public.project_boundaries FOR ALL USING (auth.role() = 'authenticated');

-- ==========================================
-- 9. STORAGE
-- ==========================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('installation-photos', 'installation-photos', true),
       ('followup-note-photos', 'followup-note-photos', true),
       ('reminder-photos', 'reminder-photos', true),
       ('qbc-storage', 'qbc-storage', true),
       ('Background', 'Background', false)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Read Storage" ON storage.objects FOR SELECT USING (true);
CREATE POLICY "Auth Manage Storage" ON storage.objects FOR ALL USING (auth.role() = 'authenticated');

-- ==========================================
-- 10. DATA MIGRATION & SEED
-- ==========================================
DO $$ BEGIN
    IF EXISTS (SELECT FROM pg_tables WHERE tablename = 'user_audit_log') THEN
        INSERT INTO public.audit_logs (action, details, created_at)
        SELECT action, details, created_at FROM public.user_audit_log
        ON CONFLICT DO NOTHING;
    END IF;

    IF EXISTS (SELECT FROM pg_tables WHERE tablename = 'reminders') THEN
        INSERT INTO public.work_order_reminders (id, title, reminder_datetime, notes, priority, status, created_at)
        SELECT id, title, reminder_datetime, notes, priority, status, created_at FROM public.reminders
        ON CONFLICT (id) DO NOTHING;
    END IF;
END $$;

INSERT INTO public.ai_settings (id, ai_enabled, provider_name, ai_model, api_base_url, api_key)
VALUES (1, true, 'BadTheory', 'gw_engineer', 'https://api.badtheorylabs.com/v1', 'redacted')
ON CONFLICT (id) DO NOTHING;

-- ==========================================
-- 11. VERIFICATION & CONSISTENCY (PHASE 5 & 6)
-- ==========================================

CREATE OR REPLACE VIEW public.verification_report AS
SELECT
    table_name,
    (SELECT count(*) FROM information_schema.columns WHERE table_name = t.table_name) as cols,
    EXISTS (SELECT 1 FROM pg_policy WHERE tablename = t.table_name) as has_rls
FROM information_schema.tables t
WHERE table_schema = 'public' AND table_name IN ('work_orders', 'profiles', 'manufacturing', 'audit_logs', 'work_order_reminders');

CREATE OR REPLACE VIEW public.consistency_orphans AS
SELECT 'manufacturing' as src, m.work_order_number FROM public.manufacturing m LEFT JOIN public.work_orders w ON m.work_order_number = w.work_order WHERE w.work_order IS NULL
UNION ALL
SELECT 'reminders' as src, r.work_order_number FROM public.work_order_reminders r LEFT JOIN public.work_orders w ON r.work_order_number = w.work_order WHERE w.work_order IS NULL;
