-- QBC SUPABASE MASTER SETUP
-- Description: Complete production-ready database migration (Fixed & Improved)
-- Version: 1.1.0
-- Date: 2024-05-24

-- ==========================================
-- 1. EXTENSIONS & ENUMS
-- ==========================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==========================================
-- 2. CORE TABLES (ENSURING EXISTENCE AND SCHEMA)
-- ==========================================

-- work_orders
CREATE TABLE IF NOT EXISTS public.work_orders (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    work_order text UNIQUE NOT NULL,
    description text,
    status text,
    pwa_engineer text,
    target_start_date timestamptz,
    target_finish_date timestamptz,
    location text,
    created_at timestamptz DEFAULT now()
);

-- Ensure all required columns exist in work_orders (Idempotent updates)
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS latitude float8;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS longitude float8;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS is_sent_to_fab boolean DEFAULT false;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS fab_history jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS style_settings jsonb DEFAULT '{}'::jsonb;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS reported_by text;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS reported_date timestamptz;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS status_update_date timestamptz;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS qbc_comments text;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS ro text;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS tdp text;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS application_date timestamptz;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS tdp_status text;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS tdp_expiry_date timestamptz;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS media_announcement text;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS last_modified_at timestamptz DEFAULT now();
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS priority text DEFAULT 'Normal';
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS month text;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS completion_status text;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS ready_for_installation boolean DEFAULT false;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS installation_status text DEFAULT 'Pending';
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS assigned_team text;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS assigned_date timestamptz;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS planned_installation_date date;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS actual_installation_date date;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS dispatch_time timestamptz;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS dispatch_user text;
ALTER TABLE public.work_orders ADD COLUMN IF NOT EXISTS sequence_order integer;

-- profiles
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email text UNIQUE NOT NULL,
    is_approved boolean DEFAULT false,
    is_admin boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS full_name text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS mobile text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS position text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role text DEFAULT 'User';

-- manufacturing
CREATE TABLE IF NOT EXISTS public.manufacturing (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    work_order_number text REFERENCES public.work_orders(work_order) ON DELETE CASCADE,
    road_catg text,
    sign_material text,
    sign_type text,
    sign_ref text,
    sign_shape text,
    sign_size text,
    sign_qty text,
    post_type text,
    post_height text,
    post_qty text,
    found_size text,
    found_qty text,
    fab_status text,
    installation_date date,
    scrap_removal text,
    fab_details text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ==========================================
-- 3. NEW TABLES & DATA MIGRATION
-- ==========================================

-- audit_logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES auth.users(id),
    user_email text,
    user_name text,
    action text NOT NULL,
    details text,
    work_order text,
    created_at timestamptz DEFAULT now()
);

DO $$ BEGIN
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'user_audit_log') THEN
        INSERT INTO public.audit_logs (created_at, action, details)
        SELECT created_at, action, details FROM public.user_audit_log
        ON CONFLICT DO NOTHING;
    END IF;
END $$;

-- work_order_reminders
CREATE TABLE IF NOT EXISTS public.work_order_reminders (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    work_order_id text,
    work_order_number text,
    work_order_title text,
    title text NOT NULL,
    reminder_datetime timestamptz NOT NULL,
    reason text,
    custom_reason text,
    notes text,
    priority text DEFAULT 'Normal',
    status text DEFAULT 'upcoming',
    assigned_to uuid REFERENCES public.profiles(id),
    assigned_to_name text,
    alarm_enabled boolean DEFAULT true,
    calendar_enabled boolean DEFAULT true,
    desktop_notif boolean DEFAULT true,
    email_enabled boolean DEFAULT false,
    snoozed_until timestamptz,
    snooze_count integer DEFAULT 0,
    is_pinned boolean DEFAULT false,
    photo_count integer DEFAULT 0,
    created_by uuid REFERENCES public.profiles(id),
    created_by_name text,
    updated_by uuid REFERENCES public.profiles(id),
    updated_at timestamptz DEFAULT now(),
    completed_at timestamptz,
    completed_by uuid REFERENCES public.profiles(id),
    created_at timestamptz DEFAULT now()
);

-- Robust migration for reminders
DO $$ BEGIN
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'reminders') THEN
        INSERT INTO public.work_order_reminders (
            id, work_order_number, work_order_title, title, reminder_datetime,
            reason, custom_reason, notes, priority, status, assigned_to, assigned_to_name,
            alarm_enabled, calendar_enabled, desktop_notif, email_enabled,
            snoozed_until, snooze_count, created_at, created_by, created_by_name,
            updated_at, updated_by, completed_at, completed_by, photo_count
        )
        SELECT
            id, work_order_number, work_order_title, title, reminder_datetime,
            reason, custom_reason, notes, priority, status, assigned_to, assigned_to_name,
            alarm_enabled, calendar_enabled, desktop_notif, email_enabled,
            snoozed_until, snooze_count, created_at, created_by, created_by_name,
            updated_at, updated_by, completed_at, completed_by, photo_count
        FROM public.reminders
        ON CONFLICT (id) DO NOTHING;
    END IF;
END $$;

-- installation_teams
CREATE TABLE IF NOT EXISTS public.installation_teams (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    team_name text UNIQUE NOT NULL,
    supervisor text,
    crew_size integer,
    capacity_per_day integer,
    vehicle_plate text,
    vehicle text,
    status text DEFAULT 'Active',
    created_at timestamptz DEFAULT now()
);

-- followup_notes
CREATE TABLE IF NOT EXISTS public.followup_notes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    body text NOT NULL,
    color text DEFAULT 'yellow',
    rotation_deg numeric DEFAULT 0,
    created_by uuid REFERENCES public.profiles(id),
    created_by_name text,
    is_archived boolean DEFAULT false,
    work_order_number text,
    tags text[],
    category text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Remaining Support Tables
CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid REFERENCES auth.users(id),
    user_name text,
    action_text text,
    work_order text,
    category text DEFAULT 'system',
    read boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.reminder_notifications (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    reminder_id uuid REFERENCES public.work_order_reminders(id) ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users(id),
    title text,
    message text,
    read boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.installation_records (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    work_order text NOT NULL,
    team_name text,
    status text,
    completion_date timestamptz,
    gps_coordinates text,
    notes text,
    signature_url text,
    recorded_by text,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.installation_activities (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    work_order text,
    action text NOT NULL,
    user_name text,
    timestamp timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.installation_photos (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    work_order text NOT NULL,
    category text NOT NULL,
    url text NOT NULL,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.work_order_comments (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    work_order text REFERENCES public.work_orders(work_order) ON DELETE CASCADE,
    content text NOT NULL,
    author_id uuid REFERENCES auth.users(id),
    author_name text,
    created_at timestamptz DEFAULT now()
);

-- ==========================================
-- 4. CONSTRAINTS & INDEXES
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_wo_number ON public.work_orders (work_order);
CREATE INDEX IF NOT EXISTS idx_mfg_wo ON public.manufacturing (work_order_number);
CREATE INDEX IF NOT EXISTS idx_rem_datetime ON public.work_order_reminders (reminder_datetime);
CREATE INDEX IF NOT EXISTS idx_audit_created ON public.audit_logs (created_at);

-- ==========================================
-- 5. STORAGE BUCKETS & POLICIES
-- ==========================================

-- Idempotent Bucket Creation
INSERT INTO storage.buckets (id, name, public)
VALUES ('installation-photos', 'installation-photos', true),
       ('followup-note-photos', 'followup-note-photos', true),
       ('reminder-photos', 'reminder-photos', true),
       ('qbc-storage', 'qbc-storage', true)
ON CONFLICT (id) DO NOTHING;

-- Storage RLS Policies
DROP POLICY IF EXISTS "Public Storage Access" ON storage.objects;
CREATE POLICY "Public Storage Access" ON storage.objects FOR SELECT
USING (bucket_id IN ('installation-photos', 'followup-note-photos', 'reminder-photos', 'qbc-storage'));

DROP POLICY IF EXISTS "Authenticated Upload" ON storage.objects;
CREATE POLICY "Authenticated Upload" ON storage.objects FOR INSERT
WITH CHECK (auth.role() = 'authenticated' AND bucket_id IN ('installation-photos', 'followup-note-photos', 'reminder-photos', 'qbc-storage'));

-- ==========================================
-- 6. RLS TABLES
-- ==========================================
ALTER TABLE public.work_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_order_reminders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Global Access" ON public.work_orders;
CREATE POLICY "Global Access" ON public.work_orders FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Global Access" ON public.work_order_reminders;
CREATE POLICY "Global Access" ON public.work_order_reminders FOR ALL USING (auth.role() = 'authenticated');

-- ==========================================
-- 7. PHASE 5 - VALIDATION
-- ==========================================
CREATE OR REPLACE VIEW public.schema_verification AS
SELECT
    t.table_name,
    (SELECT count(*) FROM information_schema.columns c WHERE c.table_name = t.table_name) as column_count,
    EXISTS (SELECT 1 FROM pg_indexes i WHERE i.tablename = t.table_name) as has_indexes,
    EXISTS (SELECT 1 FROM pg_policy p WHERE p.tablename = t.table_name) as has_rls_policies
FROM information_schema.tables t
WHERE t.table_schema = 'public'
AND t.table_name IN ('work_orders', 'profiles', 'manufacturing', 'audit_logs', 'work_order_reminders');

-- ==========================================
-- 8. PHASE 6 - CONSISTENCY CHECKS
-- ==========================================
-- Check for Orphaned Manufacturing Records
CREATE OR REPLACE VIEW public.consistency_orphans AS
SELECT 'manufacturing' as source_table, m.work_order_number as ref_id
FROM public.manufacturing m
LEFT JOIN public.work_orders w ON m.work_order_number = w.work_order
WHERE w.work_order IS NULL
UNION ALL
SELECT 'reminders' as source_table, r.work_order_number as ref_id
FROM public.work_order_reminders r
LEFT JOIN public.work_orders w ON r.work_order_number = w.work_order
WHERE w.work_order IS NULL AND r.work_order_number IS NOT NULL;

-- Check for NULLs in prohibited columns
CREATE OR REPLACE VIEW public.consistency_nulls AS
SELECT 'work_orders' as table_name, count(*) as null_wo_count
FROM public.work_orders WHERE work_order IS NULL;
