-- SQL Script to set up dedicated tables for Work Order Comments and Attachments

-- 1. Create Work Order Comments Table
CREATE TABLE IF NOT EXISTS public.work_order_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order TEXT NOT NULL,
    content TEXT NOT NULL,
    author_id UUID REFERENCES auth.users(id),
    author_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    -- Optional: Add index for performance
    CONSTRAINT fk_work_order FOREIGN KEY (work_order) REFERENCES public.work_orders(work_order) ON DELETE CASCADE
);

-- Enable RLS for Comments
ALTER TABLE public.work_order_comments ENABLE ROW LEVEL SECURITY;

-- Simple Policy: Authenticated users can read and insert comments
CREATE POLICY "Allow authenticated read comments" ON public.work_order_comments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert comments" ON public.work_order_comments FOR INSERT TO authenticated WITH CHECK (true);


-- 2. Create Work Order Attachments Table
CREATE TABLE IF NOT EXISTS public.work_order_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order TEXT NOT NULL,
    url TEXT NOT NULL,
    filename TEXT,
    file_type TEXT,
    uploader_id UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_work_order_attach FOREIGN KEY (work_order) REFERENCES public.work_orders(work_order) ON DELETE CASCADE
);

-- Enable RLS for Attachments
ALTER TABLE public.work_order_attachments ENABLE ROW LEVEL SECURITY;

-- Simple Policy: Authenticated users can read and insert attachments
CREATE POLICY "Allow authenticated read attachments" ON public.work_order_attachments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert attachments" ON public.work_order_attachments FOR INSERT TO authenticated WITH CHECK (true);


-- 3. Storage Bucket Policy (Ensure 'qbc-storage' bucket exists and has 'attachments/' folder permissions)
-- You may need to adjust these in the Supabase Dashboard -> Storage -> Policies
-- Policy: Allow authenticated users to upload to 'attachments/'
-- Policy: Allow public read to 'attachments/'
